version: "3.7"

services:
  test: &base
    image: kiwy-test
    build: .
    volumes:
      - .:/kiwy
    command: make test
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/kiwy/gcloud-credentials.json
      - BUCKET=rdsm-analytics-development

  app:
    <<: *base
    command: make run
